spring.application.name=sistema-gerenciador-inventario

spring.datasource.url=jdbc:mysql://localhost:3306/sgidb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.com.project.backend: DEBUG

jwt.secret=4F7r9z!pQx@B2sD5gT8vY1nM3kC6hJ0wRqL9eXfUoI7tZ2pL