DELIMITER $$

CREATE TRIGGER ARC_ITEM_T_SGI_PRODUCT
BEFORE INSERT ON T_SGI_PRODUCT
FOR EACH ROW
BEGIN
    DECLARE d VARCHAR(17);
    SELECT tp_item INTO d FROM T_SGI_ITEM WHERE id_item = NEW.id_item LIMIT 1;
    IF d IS NULL OR d <> 'PRODUTO' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'FK_PRODUCT_ITEM violated restriction: tp_item need to be ''PRODUTO''';
    END IF;
END$$

CREATE TRIGGER ARC_ITEM_T_SGI_RAW_MATERIAL
BEFORE INSERT ON T_SGI_RAW_MATERIAL
FOR EACH ROW
BEGIN
    DECLARE d VARCHAR(17);
    SELECT tp_item INTO d FROM T_SGI_ITEM WHERE id_item = NEW.id_item LIMIT 1;
    IF d IS NULL OR d <> 'MATERIA_PRIMA' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'FK_RAW_MATERIAL_ITEM violated restriction: tp_item need to be ''RAW_MATERIAL''';
    END IF;
END$$

DELIMITER ;